import manifest from '../../content/image-manifest.json'

/**
 * Project frontmatter refers to images by their ARCHIVE path — the true
 * original in sources/uploads. That is the stable identity, and it deliberately
 * does not change when the web master is re-encoded to a different format.
 *
 * scripts/sync-media.mjs converts 373 photographic PNGs to JPEG, so the served
 * file often has a different extension from the one in the frontmatter.
 * content/image-manifest.json is the bridge.
 *
 *     frontmatter   2025/12/LightPaint_photo01_Assal-Toudehfallah.png
 *     manifest      2025/12/LightPaint_photo01_Assal-Toudehfallah.jpg
 *     served        responsive widths + WebP/AVIF, generated by Astro
 */

const files = import.meta.glob<{ default: ImageMetadata }>(
  '/content/images/**/*.{jpg,jpeg,png,gif,webp}',
  { eager: true },
)

type ManifestEntry = { file: string; bytes: number; width: number | null; height: number | null }
const index = manifest.images as Record<string, ManifestEntry>

export function resolveImage(archivePath: string): ImageMetadata | null {
  const entry = index[archivePath]
  if (!entry) return null
  return files[`/content/images/${entry.file}`]?.default ?? null
}

export function imageDimensions(archivePath: string) {
  const entry = index[archivePath]
  return entry ? { width: entry.width, height: entry.height } : null
}

/** Images the build could not resolve — surfaced rather than rendered blank. */
export function missingImages(paths: string[]): string[] {
  return paths.filter((p) => !resolveImage(p))
}
